from django.urls import path
from . import views, auto_views, report_views

urlpatterns = [ 
    path('home', views.index, name='index'),
    path('assistances/list', views.assistances_list, name='assistances-list'),
    path('assistances/search', views.assistances_search, name='assistances-search'),
    path('assistances/form', views.assistances_form, name='assistances-form'),
    path('assistances/form-save', views.assistances_form_save, name='assistances-form-save'),
    path('assistances/remove', views.assistances_remove, name='assistances-remove'),
    path('assistances/client/<int:client_id>/', views.assistances_client, name='assistances-client'),
    path('assistances/search-emp', views.assistances_search_emp, name='assistances-search-emp'),
    path('assistances/search-cli', views.assistances_search_cli, name='assistances-search-cli'),

    #---------------------- EMPLOYEES -----------------------
    path('employees', views.employees, name='employees'),
    path('employees/list', views.employees_list, name='employees-list'),
    path('employees/search', views.employees_search, name='employees-search'),
    path('employees/page-rows/<int:page>/', views.employees_page_rows, name='employees-page-rows'),
    path('employees/page-rows/<int:page>/<int:rows>', views.employees_page_rows, name='employees-page-rows'),
    path('employees/form', views.employees_form, name='employees-form'),
    path('employees/remove', views.employees_remove, name='employees-remove'),
    path('employees/new', views.employees_new, name='employees-new'),
    path('employees/check-dni', views.employees_check_dni, name='employees-check-dni'),
    path('employees/save-email', views.employees_save_email, name='employees-save-email'),
    path('employees/save-cat', views.employees_save_cat, name='employees-save-cat'),
    path('employees/save-dni', views.employees_save_dni, name='employees-save-dni'),
    path('employees/form/timetable', views.employees_form_timetable, name='employees-form-timetable'),
    path('employees/form/timetable/remove', views.employees_form_timetable_remove, name='employees-form-timetable-remove'),
    path('employees/export', views.employees_export, name='employees-export'),
    path('employees/import-csv', views.employees_import_csv, name='employees-import-csv'),
    path('employees/import', views.employees_import, name='employees-import'),
    path('employees/copy-pin', views.employees_copy_pin, name='employees-copy-pin'),
    path('employees/doc-add/', views.employees_doc_add, name='employees-doc-add'),
    path('employees/doc-remove/', views.employees_doc_remove, name='employees-doc-remove'),
    path('employees/search-city', views.employees_search_city, name='employees-search-city'),

    path('employees/timetable/<int:obj_id>', views.employees_timetable, name='employees-timetable'),
    path('employees/timetable/load', views.employees_timetable_load, name='employees-timetable-load'),
    path('employees/timetable/assign', views.employees_timetable_assign, name='employees-timetable-assign'),
    #path('employees/timetable/assign-save', views.employees_timetable_assign_save, name='employees-timetable-assign-save'),
    path('employees/timetable/assign-save2', views.employees_timetable_assign_save2, name='employees-timetable-assign-save2'),
    path('employees/timetable/assign-edit', views.employees_timetable_assign_edit, name='employees-timetable-assign-edit'),
    #path('employees/timetable/assign-remove', views.employees_timetable_assign_remove, name='employees-timetable-assign-remove'),
    path('employees/timetable/change-status', views.employees_timetable_change_status, name='employees-timetable-change-status'),
    path('employees/timetable/set-status', views.employees_timetable_set_status, name='employees-timetable-set-status'),
    path('employees/timetable/clients-add', views.employees_timetable_clients_add, name='employees-timetable-clients-add'),
    path('employees/timetable/clients-save', views.employees_timetable_clients_save, name='employees-timetable-clients-save'),
    path('employees/timetable/clients-remove', views.employees_timetable_clients_remove, name='employees-timetable-clients-remove'),

    #---------------------- EMPLOYEE -----------------------
    path('employee/<int:obj_id>', views.employee, name='employee'),
    path('employee/search', views.employee_search, name='employee-search'),
    path('employee/search-client', views.employee_search_client, name='employee-search-client'),
    path('employee/form/timetable', views.employee_form_timetable, name='employee-form-timetable'),
    path('employee/form/timetable/remove/<int:obj_id>', views.employee_form_timetable_remove, name='employee-form-timetable-remove'),

    #------------------------- CLIENTS -----------------------
    path('clients', views.clients, name='clients'),
    path('clients/list', views.clients_list, name='clients-list'),
    path('clients/search', views.clients_search, name='clients-search'),
    path('clients/form', views.clients_form, name='clients-form'),
    path('clients/form/save', views.clients_form_save, name='clients-form-save'),
    path('clients/details/<int:obj_id>', views.clients_details, name='clients-details'),
    path('clients/form/timetable', views.clients_form_timetable, name='clients-form-timetable'),
    path('clients/remove', views.clients_remove, name='clients-remove'),
    path('clients/form/timetable/remove', views.clients_form_timetable_remove, name='clients-form-timetable-remove'),
    path('clients/print-all-qr', views.clients_print_all_qr, name='clients-print-all-qr'),
    path('clients/print-qr/<int:obj_id>', views.clients_print_qr, name='clients-print-qr'),
    path('clients/assistances/<int:obj_id>', views.clients_assistances, name='clients-assistances'),
    path('clients/import-csv/', views.clients_import_csv, name='clients-import-csv'),
    path('clients/export-csv/', views.clients_export_csv, name='clients-export-csv'),
    path('clients/import/', views.clients_import, name='clients-import'),
    path('clients/doc-add/', views.clients_doc_add, name='clients-doc-add'),
    path('clients/doc-remove/', views.clients_doc_remove, name='clients-doc-remove'),
    path('clients/type-add/', views.clients_type_add, name='clients-type-add'),
    path('clients/type-remove/', views.clients_type_remove, name='clients-type-remove'),
    path('clients/inactive-confirm/', views.clients_inactive_confirm, name='clients-inactive-confirm'),
    path('clients/inactive-set/', views.clients_inactive_set, name='clients-inactive-set'),
    path('clients/inactive-add/', views.clients_inactive_add, name='clients-inactive-add'),
    path('clients/inactive-remove/', views.clients_inactive_remove, name='clients-inactive-remove'),
    path('clients/stopped-confirm/', views.clients_stopped_confirm, name='clients-stopped-confirm'),
    path('clients/stopped-set/', views.clients_stopped_set, name='clients-stopped-set'),
    path('clients/stopped-add/', views.clients_stopped_add, name='clients-stopped-add'),
    path('clients/stopped-remove/', views.clients_stopped_remove, name='clients-stopped-remove'),
    path('clients/search-city', views.clients_search_city, name='clients-search-city'),

    path('clients/timetable/<int:obj_id>', views.clients_timetable, name='clients-timetable'),
    path('clients/timetable/employees-add', views.clients_timetable_employees_add, name='clients-timetable-employees-add'),
    path('clients/timetable/employees-save', views.clients_timetable_employees_save, name='clients-timetable-employees-save'),
    path('clients/timetable/employees-remove', views.clients_timetable_employees_remove, name='clients-timetable-employees-remove'),
    path('clients/timetable/load', views.clients_timetable_load, name='clients-timetable-load'),
    path('clients/timetable/assign', views.clients_timetable_assign, name='clients-timetable-assign'),
    path('clients/timetable/assign-save', views.clients_timetable_assign_save, name='clients-timetable-assign-save'),
    path('clients/timetable/assign-save2', views.clients_timetable_assign_save2, name='clients-timetable-assign-save2'),
    path('clients/timetable/assign-edit', views.clients_timetable_assign_edit, name='clients-timetable-assign-edit'),
    path('clients/timetable/assign-remove', views.clients_timetable_assign_remove, name='clients-timetable-assign-remove'),

    #---------------------- ASSISTANCES -----------------------
    path('report', report_views.report, name='report'),
    path('report/clients', report_views.report_clients, name='report-clients'),
    path('report/clients/list', report_views.report_clients_list, name='report-clients-list'),
    path('report/clients/search', report_views.report_clients_search, name='report-clients-search'),
    path('report/assistances', report_views.report_assistances, name='report-assistances'),
    path('report/assistances/list', report_views.report_assistances_list, name='report-assistances-list'),
    path('report/assistances/search', report_views.report_assistances_search, name='report-assistances-search'),
    path('report/export', report_views.report_export, name='report-export'),
    path('report/export-emp', report_views.report_export_emp, name='report-export-emp'),
    #path('report/search-emp', report_views.report_search_emp, name='report-search-emp'),
    #path('report/search-emp-cli', report_views.report_search_emp_cli, name='report-search-emp-cli'),
    path('report/search-cli', report_views.report_search_cli, name='report-search-cli'),
    path('report/employees', report_views.report_employees, name='report-employees'),
    path('report/employees/list', report_views.report_employees_list, name='report-employees-list'),
    path('report/employees/search', report_views.report_employees_search, name='report-employees-search'),
    path('report/emp-cli-status', report_views.report_emp_cli_status, name='report-emp-cli-status'),
    path('report/emp-cli-status-search', report_views.report_emp_cli_status_search, name='report-emp-cli-status-search'),
    path('report/emp-cli-status-export', report_views.report_emp_cli_status_export, name='report-emp-cli-status-export'),

    #---------------------- INCIDENTS -----------------------
    path('incidents', views.incidents, name='incidents'),
    path('incidents/list', views.incidents_list, name='incidents-list'),
    path('incidents/search', views.incidents_search, name='incidents-search'),
    path('incidents/form', views.incidents_form, name='incidents-form'),

    #---------------------- AUTO -----------------------
    path('autosave_field/', auto_views.autosave_field, name='autosave_field'),
    path('autosave_fields/', auto_views.autosave_fields, name='autosave_fields'),
    path('autoremove_obj/', auto_views.autoremove_obj, name='autoremove_obj'),
    path('autocomplete_search/', auto_views.autocomplete_search, name='autocomplete_search'),
]

